### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by Anjan50** [Anjan50/CSE-5B1-TimeTable#3]
Add favicon beside Title

![Favicon](https://raw.githubusercontent.com/Anjan50/CSE-5B1-TimeTable/new-branch/issue-Add%20favicon.png)

**Comment by Aman-king** [comment]
I will Add favicon.ico 
assign me

**Comment by Anjan50** [comment]
> I will Add favicon.ico
> assign me

Yeah sure @Aman-king 
I'll accept

**Comment by Anjan50** [comment]
Well did @Aman-king 
Your PR accepted
